config/routes.rb
Church::Application.routes.draw do
  resources :regs

end

app/models/reg.rb
class Reg < ActiveRecord::Base
  attr_accessible :background, :email, :fname, :lname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/regs_controller.rb
class RegsController < ApplicationController
  # GET /regs
  # GET /regs.json
  def index
    @regs = Reg.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @regs }
    end
  end

  # GET /regs/1
  # GET /regs/1.json
  def show
    @reg = Reg.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reg }
    end
  end

  # GET /regs/new
  # GET /regs/new.json
  def new
    @reg = Reg.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reg }
    end
  end

  # GET /regs/1/edit
  def edit
    @reg = Reg.find(params[:id])
  end

  # POST /regs
  # POST /regs.json
  def create
    @reg = Reg.new(params[:reg])

    respond_to do |format|
      if @reg.save
        format.html { redirect_to @reg, notice: 'Reg was successfully created.' }
        format.json { render json: @reg, status: :created, location: @reg }
      else
        format.html { render action: "new" }
        format.json { render json: @reg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /regs/1
  # PUT /regs/1.json
  def update
    @reg = Reg.find(params[:id])

    respond_to do |format|
      if @reg.update_attributes(params[:reg])
        format.html { redirect_to @reg, notice: 'Reg was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regs/1
  # DELETE /regs/1.json
  def destroy
    @reg = Reg.find(params[:id])
    @reg.destroy

    respond_to do |format|
      format.html { redirect_to regs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/regs_helper.rb
module RegsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Church</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/regs/_form.html.erb
<%= form_for(@reg) do |f| %>
  <% if @reg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reg.errors.count, "error") %> prohibited this reg from being saved:</h2>

      <ul>
      <% @reg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :background %><br />
    <%= f.text_area :background %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regs/edit.html.erb
<h1>Editing reg</h1>

<%= render 'form' %>

<%= link_to 'Show', @reg %> |
<%= link_to 'Back', regs_path %>

app/views/regs/index.html.erb
<h1>Listing regs</h1>

<table>
  <tr>
    <th>Fname</th>
    <th>Lname</th>
    <th>Email</th>
    <th>Background</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @regs.each do |reg| %>
  <tr>
    <td><%= reg.fname %></td>
    <td><%= reg.lname %></td>
    <td><%= reg.email %></td>
    <td><%= reg.background %></td>
    <td><%= link_to 'Show', reg %></td>
    <td><%= link_to 'Edit', edit_reg_path(reg) %></td>
    <td><%= link_to 'Destroy', reg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reg', new_reg_path %>

app/views/regs/new.html.erb
<h1>New reg</h1>

<%= render 'form' %>

<%= link_to 'Back', regs_path %>

app/views/regs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fname:</b>
  <%= @reg.fname %>
</p>

<p>
  <b>Lname:</b>
  <%= @reg.lname %>
</p>

<p>
  <b>Email:</b>
  <%= @reg.email %>
</p>

<p>
  <b>Background:</b>
  <%= @reg.background %>
</p>


<%= link_to 'Edit', edit_reg_path(@reg) %> |
<%= link_to 'Back', regs_path %>